url: 'https://flavorpacket.io' # the base hostname & protocol
baseurl: '' # subpath of your site, e.g. /blog
title: 'FlavorPacket.io'

plugins:
  - jekyll-postcss-v2

sass:
  sourcemap: never

postcss:
  cache: false

exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - README.md

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map

colors:
  fg: 'text-amber-300 text-shadow-lg'
  bg: 'bg-pink-500'

# site-wide content for my OCs
oc_index:
  astra: 0
  li-wei: 1
  roxy: 2
  pixel: 3
  prism: 4

ocs:
  - name: Astra
    term: astra
    pronouns: She/Her
    fg_color: text-white
    bg_color: bg-pink-500
  - name: Li Wei
    term: li-wei
    pronouns: She/Her
    fg_color: text-amber-200
    bg_color: bg-green-800
  - name: Roxy
    term: roxy
    pronouns: She/Her
    fg_color: text-blue-600
    bg_color: bg-orange-400
  - name: Pixel
    term: pixel
    pronouns: She/Her
    fg_color: text-pink-500
    bg_color: bg-yellow-300
  - name: Prism
    term: prism
    pronouns: She/Her
    fg_color: text-blue-600
    bg_color: bg-pink-400
