url: 'https://flavorpacket.io' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '' # the subpath of your site, e.g. /blog
title: 'FlavorPacket.io' # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss-v2

sass:
  sourcemap: never

postcss:
  cache: false

exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - README.md

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map
